#INCLUDE <16F887.H>
#FUSES HS, PUT
#USE DELAY(CLOCK=20M)

#define LCD_ENABLE_PIN  PIN_E0
#define LCD_RS_PIN      PIN_E1
#define LCD_RW_PIN      PIN_E2
#define LCD_DATA4       PIN_D4
#define LCD_DATA5       PIN_D5
#define LCD_DATA6       PIN_D6
#define LCD_DATA7       PIN_D7

#INCLUDE <LCD.C>

UNSIGNED INT8 XX = 16;
UNSIGNED INT8 YY = 32;
UNSIGNED INT8 GIO = 17;
UNSIGNED INT8 PHUT = 32;
UNSIGNED INT8 GIAY = 45;


VOID MAIN(){
   SET_TRIS_D(0);
   SET_TRIS_E(0);
   
   LCD_INIT();
   
   WHILE(TRUE){
      LCD_GOTOXY(1,1);
      PRINTF(LCD_PUTC, "SPT:%02U     SPK:%02U", XX, YY);
      LCD_GOTOXY(4,2);
      PRINTF(LCD_PUTC, "%02U %02U %02U", GIO, PHUT, GIAY);
   }
}

